"""
Export an answered question as a standalone report - Markdown or PDF - with
every citation embedded and linked back to its source page. This is the
"notes / export" feature: turn a verified answer into something a user can
save, share, or attach to a ticket without losing the provenance that makes
it trustworthy in the first place.

Markdown and PDF share one input shape (ExportRequest) and are generated
independently so either can be added/changed without touching the other.
"""
from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

from app.api.schemas import ExportRequest


def _source_url(base_url: str, document_id: str, page_number: int) -> str:
    base = base_url.rstrip("/")
    return f"{base}/api/documents/{document_id}/file#page={page_number}"


def generate_markdown(export: ExportRequest, base_url: str) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# DocIntel Answer Report",
        "",
        f"*Generated {generated_at}*",
        "",
        "## Question",
        "",
        export.question,
        "",
        "## Answer",
        "",
        export.answer,
        "",
    ]
    if export.refused:
        lines.append("> ⚠️ The system withheld or refused this answer - see above for why.")
        lines.append("")
    lines.append(f"**Groundedness:** {export.groundedness_coverage * 100:.0f}% of answer sentences carry a resolvable citation.")
    lines.append("")
    if export.sub_queries and len(export.sub_queries) > 1:
        lines.append("**Question was decomposed into:**")
        for sq in export.sub_queries:
            lines.append(f"- {sq}")
        lines.append("")

    lines.append("## Sources")
    lines.append("")
    if not export.citations:
        lines.append("*No citations - the documents did not support a grounded answer.*")
    for i, c in enumerate(export.citations, start=1):
        url = _source_url(base_url, c.document_id, c.page_number)
        lines.append(f"**[{i}] {c.document_name}, page {c.page_number}** — [open source]({url})")
        lines.append("")
        lines.append(f"> {c.snippet}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by DocIntel - Multimodal Document Intelligence.*")
    return "\n".join(lines)


def generate_pdf(export: ExportRequest, base_url: str) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
        title="DocIntel Answer Report",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Heading1"], fontSize=18, spaceAfter=4, textColor=colors.HexColor("#1a1f2b")
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"], fontSize=9, textColor=colors.grey, spaceAfter=14
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=12,
        spaceBefore=14,
        spaceAfter=6,
        textColor=colors.HexColor("#1a1f2b"),
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=10.5, leading=15, alignment=TA_LEFT
    )
    citation_style = ParagraphStyle(
        "Citation", parent=styles["Normal"], fontSize=9.5, leading=13.5, spaceAfter=2
    )
    snippet_style = ParagraphStyle(
        "Snippet",
        parent=styles["Normal"],
        fontSize=9,
        leading=13,
        leftIndent=12,
        textColor=colors.HexColor("#3a3f4b"),
        spaceAfter=10,
    )
    warning_style = ParagraphStyle(
        "Warning", parent=styles["Normal"], fontSize=9.5, textColor=colors.HexColor("#9a5b00"), spaceAfter=8
    )

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story = [
        Paragraph("DocIntel Answer Report", title_style),
        Paragraph(f"Generated {generated_at}", meta_style),
        Paragraph("Question", heading_style),
        Paragraph(_escape(export.question), body_style),
        Paragraph("Answer", heading_style),
        Paragraph(_escape(export.answer), body_style),
        Spacer(1, 6),
    ]

    if export.refused:
        story.append(Paragraph("⚠ The system withheld or refused this answer - see above for why.", warning_style))

    coverage_pct = export.groundedness_coverage * 100
    story.append(
        Paragraph(
            f"<b>Groundedness:</b> {coverage_pct:.0f}% of answer sentences carry a resolvable citation.",
            meta_style,
        )
    )

    if export.sub_queries and len(export.sub_queries) > 1:
        story.append(Paragraph("Question was decomposed into:", heading_style))
        for sq in export.sub_queries:
            story.append(Paragraph(f"• {_escape(sq)}", body_style))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc"), spaceBefore=12, spaceAfter=10))
    story.append(Paragraph("Sources", heading_style))

    if not export.citations:
        story.append(Paragraph("No citations - the documents did not support a grounded answer.", body_style))
    for i, c in enumerate(export.citations, start=1):
        url = _source_url(base_url, c.document_id, c.page_number)
        story.append(
            Paragraph(
                f'[{i}] <b>{_escape(c.document_name)}</b>, page {c.page_number} '
                f'&nbsp;—&nbsp; <link href="{url}" color="blue">open source</link>',
                citation_style,
            )
        )
        story.append(Paragraph(f"&ldquo;{_escape(c.snippet)}&rdquo;", snippet_style))

    doc.build(story)
    return buffer.getvalue()


def _escape(text: str) -> str:
    """Minimal escaping for reportlab's mini-HTML paragraph markup."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\n", "<br/>")
    )
